version: '3.5'

networks:
    default-network:
        name: default-network

services:
  #API
    proposal-webapi:
        build:
            context: .
            dockerfile: Proposal.WebApi/Proposal.WebApi.Dockerfile
        restart: always
        ports: 
            - "9000:80"
        environment:
        #DB
            - DbConnectionString=Server=proposal-database;Database=Attendance.Proposals;User Id=sa;[changed_with_no_reason]
        networks:
            - default-network
        depends_on:
            - proposal-database
    proposal-database:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            [changed_with_no_reason]: [changed_with_no_reason]
            ACCEPT_EULA: "Y"
        networks:
            - default-network
    